server:
  port: 4004
spring:
  application:
    name: API-Gateway
#Let the could search & also allow the lower case
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #by default it is false
          lower-case-service-id: true
#routing
      mvc:
        routes:
        - id: User Service
          uri: lb://UserService
          predicates:
          - path=/users/**
          
        - id: Hotel Service
          uri: lb://HotelService
          predicates:
          - path=/hotel/**
        
        - id: Rating Service        
          uri: lb://RatingService
          predicates:
          - path=/rating/**
#Eureka server (no need for this configuration for 8761 port)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true #by default true
    fetch-registry: true #by default true
  instance:
    prefer-ip-address: true #by dafault false         